version: '3.9'
services:
  prometheus:
    image: prom/prometheus:latest
    container_name: celestial_prometheus
    restart: unless-stopped
    volumes:
      - ./prometheus_scrape_example.yml:/etc/prometheus/prometheus.yml:ro
      - ./prometheus_rules.yml:/etc/prometheus/prometheus_rules.yml:ro
    command: ["--config.file=/etc/prometheus/prometheus.yml","--web.enable-lifecycle"]
    ports:
      - "9091:9090"
  grafana:
    image: grafana/grafana:latest
    container_name: celestial_grafana
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    depends_on:
      - prometheus
