global:
  scrape_interval: 15s
  evaluation_interval: 30s

rule_files:
  - prometheus_rules.yml

scrape_configs:
  - job_name: 'wechat'
    metrics_path: /wechat_metrics
    static_configs:
      - targets: ['your.domain.com']
    scheme: https  # 若未启用HTTPS，可改为 http

  - job_name: 'celestial_api'
    metrics_path: /api_metrics
    static_configs:
      - targets: ['your.domain.com']
    scheme: https
