name: Publish visualizations to GitHub Pages

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  publish:
    name: Publish reports/visualization to Pages
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Deploy `reports/visualization` to gh-pages branch
        uses: peaceiris/actions-gh-pages@v4
        with:
          publish_dir: ./reports/visualization
          publish_branch: gh-pages
          allow_empty_commit: true
          github_token: ${{ secrets.GITHUB_TOKEN }}

